<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Hawkins_SC_WebUI-fdfe86cf-12be-41d5-84c2-a14b941ca836</UserSecretsId>
    <RootNamespace>Hawkins_SC_WebUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hawkins-SC DataAccess\Hawkins-SC DataAccess.csproj" />
    <ProjectReference Include="..\Hawkins-SC Bussines\Hawkins-SC Bussines.csproj" />
    <ProjectReference Include="..\Hawkins SC\Hawkins-SC Entitys.csproj" />
    <ProjectReference Include="..\Hawkins-SC Entitys\Hawkins-SC Entitys.csproj" />
  </ItemGroup>

</Project>
